# Generated by Django 4.0.4 on 2022-05-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_weather_day_alter_weather_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='district',
        ),
        migrations.AlterField(
            model_name='weather',
            name='day',
            field=models.IntegerField(max_length=128),
        ),
        migrations.AlterField(
            model_name='weather',
            name='rain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tmax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tmin',
            field=models.FloatField(),
        ),
    ]
