# Generated by Django 4.0.4 on 2022-05-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_postmessage_soil_user_replymessage_postmessage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.RemoveField(
            model_name='postmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='replymessage',
            name='PostMessage',
        ),
        migrations.DeleteModel(
            name='Soil',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='PostMessage',
        ),
        migrations.DeleteModel(
            name='ReplyMessage',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
