# Generated by Django 4.0.4 on 2022-05-28 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0004_soil_district_weather_district_analyzeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzeddata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='replymessage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
