# Generated by Django 4.0.4 on 2022-05-28 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0005_alter_analyzeddata_date_alter_comments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzeddata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 54, 38, 704815)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 54, 38, 704815)),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 54, 38, 704815)),
        ),
        migrations.AlterField(
            model_name='replymessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 18, 54, 38, 704815)),
        ),
    ]
