# Generated by Django 4.0.4 on 2022-05-28 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapi', '0006_alter_analyzeddata_date_alter_comments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzeddata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 19, 11, 46, 235257)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 19, 11, 46, 235257)),
        ),
        migrations.AlterField(
            model_name='postmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 19, 11, 46, 235257)),
        ),
        migrations.AlterField(
            model_name='replymessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 19, 11, 46, 235257)),
        ),
    ]
